<?xml version="1.0" ?>
<robot name="infant" xmlns:xacro="http://ros.org/wiki/xacro">
	
	<!-- constants for robot dimentions -->
	<xacro:property name="pi" value="3.141592"/>
	<xacro:property name="battery_depth" value="0.420"/>
	<xacro:property name="battery_width" value="0.170"/>
	<xacro:property name="battery_height" value="0.370"/>
	<xacro:property name="rocker_bogie_back_depth" value="0.46056514"/>
	<xacro:property name="rocker_bogie_back_width" value="0.09383127"/>	
	<xacro:property name="rocker_bogie_back_height" value="0.230"/>
	<xacro:property name="rocker_bogie_front_depth" value="0.42535668"/>
	<xacro:property name="rocker_bogie_front_width" value="0.11153324"/>
	<xacro:property name="rocker_bogie_front_height" value="0.230"/>
	<xacro:property name="caster_small_length" value="0.065"/>
	<xacro:property name="caster_small_radius" value="0.010"/>
	<xacro:property name="caster_large_length" value="0.045"/>
	<xacro:property name="caster_large_radius" value="0.010"/>
	<xacro:property name="velodyne_base_length" value="0.0586740"/>
	<xacro:property name="velodyne_diameter" value="0.0853440"/>
	<xacro:property name="velodyne_top_length" value="0.0835714"/>
	<xacro:property name="velodyne_laser_depth" value="0.03475311"/>
	<xacro:property name="velodyne_laser_height" value="0.0404979"/>
	<xacro:property name="velodyne_laser_width" value="0.0468099"/>
	
	<!-- inertial for box -->
	<xacro:macro 
		name="default_box_inertial" 
		params="mass depth width height x_offset y_offset z_offset">
		<inertial>
			<origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia 
				ixx="${1/12*mass*(width*width+height*height)}" ixy="0.0" ixz="0.0" 
				iyy="${1/12*mass*(height*height+depth*depth)}" iyz="0.0" 
				izz="${1/12*mass*(depth*depth+width*width)}"/>
		</inertial>
	</xacro:macro>

	<!-- inertial for cylinder -->
	<xacro:macro 
		name="default_cylinder_inertial" 
		params="mass length radius x_offset y_offset z_offset">
		<inertial>
			<origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia 
				ixx="${1/12*mass*(3*radius*radius+length*length)}" ixy="0.0" ixz="0.0" 
				iyy="${1/12*mass*(3*radius*radius+length*length)}" iyz="0.0" 
				izz="${1/2*mass*radius*radius}"/>
		</inertial>
	</xacro:macro>

	<!-- inertial for wheel -->
	<xacro:macro 
		name="default_wheel_inertial" 
		params="mass length radius x_offset y_offset z_offset">
		<inertial>
			<origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>	
			<mass value="${mass}"/>
			<inertia 
				ixx="${1/12*mass*(3*radius*radius+length*length)}" ixy="0.0" ixz="0.0" 
				iyy="${1/2*mass*radius*radius}" iyz="0.0" 
				izz="${1/12*mass*(3*radius*radius+length*length)}"/>
		</inertial>
	</xacro:macro>

	<!-- import Rviz color -->
	<xacro:include filename="$(find infant_description)/materials/materials.xacro"/>

	<!-- import all Gazebo-customization elements, including Gazebo colors -->
	<xacro:include filename="$(find infant_description)/urdf/infant.gazebo.xacro"/>
	
	<link name="base_link"/>

	<joint name="base_to_battery_joint" type="fixed">
		<parent link="base_link"/>
		<child link="battery_link"/>
		<origin xyz="0 0 0.140" rpy="0 0 0"/>
	</joint>

	<link name="battery_link">
		<visual>
			<geometry>
				<box size="${battery_depth} ${battery_width} ${battery_height}"/>
			</geometry>
			<origin xyz="0 0 0.085" rpy="0 0 0"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<box size="${battery_depth} ${battery_width} ${battery_height}"/>
			</geometry>
			<origin xyz="0 0 0.085" rpy="0 0 0"/>
		</collision>
		<xacro:default_box_inertial 
			mass="40" depth="${battery_depth}" width="${battery_width}" height="${battery_height}"
			x_offset="0.0" y_offset="0.0" z_offset="0.085"/>
	</link>

	<xacro:macro name="rocker_bogie_back" params="prefix reflect1 reflect2">
		<joint name="rocker_bogie_back_${prefix}_joint" type="fixed">
			<parent link="battery_link"/>
			<child link="rocker_bogie_back_${prefix}_link"/>
			<origin xyz="0 ${reflect1*0.085} 0" rpy="0 0 0"/>
		</joint>
		
		<link name="rocker_bogie_back_${prefix}_link">
			<visual>
				<geometry>
					<mesh filename="package://infant_description/meshes/rocker_bogie_parts_back_${prefix}.dae"/>
				</geometry>
				<origin xyz="0 ${reflect2*(-0.020)} 0" rpy="0 ${pi} 0"/>
			</visual>
			<collision>
				<geometry>
					<box size="${rocker_bogie_back_depth} ${rocker_bogie_back_width} ${rocker_bogie_back_height}"/>
				</geometry>
				<origin 
					xyz="-${(rocker_bogie_back_depth/2)-0.080} ${reflect1*(rocker_bogie_back_width/2)} 0.035" rpy="0 0 0"/>
			</collision>
			<xacro:default_box_inertial 
				mass="5" 
				depth="${rocker_bogie_back_depth}" 
				width="${rocker_bogie_back_width}" 
				height="${rocker_bogie_back_height}" 
				x_offset="-${(rocker_bogie_back_depth/2)-0.080}" 
				y_offset="${reflect1*(rocker_bogie_back_width/2)}" 
				z_offset="0.035"/>
		</link>
	</xacro:macro>

	<xacro:rocker_bogie_back prefix="left" reflect1="1" reflect2="0"/>
	<xacro:rocker_bogie_back prefix="right" reflect1="-1" reflect2="1"/>

	<xacro:macro name="rocker_bogie_front" params="prefix reflect1 reflect2">
		<joint name="rocker_bogie_front_${prefix}_joint" type="fixed">
			<parent link="battery_link"/>
			<child link="rocker_bogie_front_${prefix}_link"/>
			<origin xyz="0 ${reflect1*0.105} 0" rpy="0 0 0"/>
		</joint>
	
		<link name="rocker_bogie_front_${prefix}_link">
			<visual>
				<geometry>
					<mesh filename="package://infant_description/meshes/rocker_bogie_parts_front_${prefix}.dae"/>
				</geometry>
				<origin xyz="0 ${reflect2*(0.020)} 0" rpy="${pi} 0 0"/>
			</visual>
			<collision>
				<geometry>
					<box size="${rocker_bogie_front_depth} ${rocker_bogie_front_width} ${rocker_bogie_front_height}"/>
				</geometry>
				<origin xyz="${(rocker_bogie_front_depth/2)-0.080} ${reflect1*(rocker_bogie_front_width/2)} 0.035" rpy="0 0 0"/>
			</collision>
			<xacro:default_box_inertial 
				mass="5" 
				depth="${rocker_bogie_front_depth}"
				width="${rocker_bogie_front_width}"
				height="${rocker_bogie_front_height}"
				x_offset="${(rocker_bogie_front_depth/2)-0.080}"
				y_offset="${reflect1*(rocker_bogie_front_width/2)}"
				z_offset="0.035"/>

		</link>
	</xacro:macro>

	<xacro:rocker_bogie_front prefix="left" reflect1="1" reflect2="1"/>
	<xacro:rocker_bogie_front prefix="right" reflect1="-1" reflect2="0"/>

	<xacro:macro name="caster_small" params="prefix reflect">
		<joint name="caster_small_${prefix}_joint" type="fixed">
			<parent link="rocker_bogie_back_${prefix}_link"/>
			<child link="caster_small_${prefix}_link"/>
			<origin xyz="-0.360 ${reflect*0.075} 0.070" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
		</joint>
	
		<link name="caster_small_${prefix}_link">
			<visual>
				<geometry>
					<mesh filename="package://infant_description/meshes/caster_small.dae"/>
				</geometry>
				<origin xyz="0 0 0" rpy="-${pi/2} 0 ${pi/2}"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="${caster_small_length}" radius="${caster_small_radius}"/>
				</geometry>
				<origin xyz="0 0 -${caster_small_length/2}" rpy="0 0 0"/>
			</collision>
			<xacro:default_cylinder_inertial 
				mass="0.5" length="${caster_small_length}" radius="${caster_small_radius}"
				x_offset="0.0" y_offset="0.0" z_offset="-${caster_small_length/2}"/>
		</link>
	</xacro:macro>
	
	<xacro:caster_small prefix="left" reflect="1"/>
	<xacro:caster_small prefix="right" reflect="-1"/>

	<xacro:macro name="caster_large" params="prefix reflect">
		<joint name="caster_large_${prefix}_joint" type="fixed">
			<parent link="rocker_bogie_front_${prefix}_link"/>
			<child link="caster_large_${prefix}_link"/>
			<origin xyz="0.330 ${reflect*0.095} 0.070" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
		</joint>
	
		<link name="caster_large_${prefix}_link">
			<visual>
				<geometry>
					<mesh filename="package://infant_description/meshes/caster_large.dae"/>
				</geometry>
				<origin xyz="0 0 0" rpy="-${pi/2} 0 ${pi/2}"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="${caster_large_length}" radius="${caster_large_radius}"/>
				</geometry>
				<origin xyz="0 0 -${caster_large_length/2}" rpy="0 0 0"/>
			</collision>
			<xacro:default_cylinder_inertial 
				mass="0.5" length="${caster_large_length}" radius="${caster_large_radius}"
				x_offset="0.0" y_offset="0.0" z_offset="-${caster_large_length/2}"/>
		</link>
	</xacro:macro>

	<xacro:caster_large prefix="left" reflect="1"/>
	<xacro:caster_large prefix="right" reflect="-1"/>
	
	<xacro:macro name="wheel" params="prefix reflect">
		<joint name="wheel_${prefix}_joint" type="continuous">
			<parent link="rocker_bogie_front_${prefix}_link"/>
			<child link="wheel_${prefix}_link"/>
			<origin xyz="0 ${reflect*0.145} 0" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
		</joint>
	
		<link name="wheel_${prefix}_link">
			<visual>
				<geometry>
					<cylinder length="0.100" radius="0.14240"/>
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<material name="ivory"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="0.100" radius="0.14240"/>
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
			</collision>
			<xacro:default_wheel_inertial 
				mass="4" length="0.100" radius="0.142240" 
				x_offset="0.0" y_offset="0.0" z_offset="0.0"/>
		</link>
	</xacro:macro>

	<xacro:wheel prefix="left" reflect="1"/>
	<xacro:wheel prefix="right" reflect="-1"/>

	<xacro:macro name="wheel_small" params="prefix">
		<joint name="wheel_small_${prefix}_joint" type="fixed">
			<parent link="caster_small_${prefix}_link"/>
			<child link="wheel_small_${prefix}_link"/>
			<origin xyz="0 0 -0.145" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
		</joint>
	
		<link name="wheel_small_${prefix}_link">
			<visual>
				<geometry>
					<cylinder length="0.030" radius="0.070"/>
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<material name="black"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="0.030" radius="0.070"/>
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
			</collision>
			<xacro:default_wheel_inertial 
				mass="1.5" length="0.030" radius="0.070"
				x_offset="0.0" y_offset="0.0" z_offset="0.0"/>
		</link>
	</xacro:macro>

	<xacro:wheel_small prefix="left"/>
	<xacro:wheel_small prefix="right"/>

	<xacro:macro name="wheel_large" params="prefix">
		<joint name="wheel_large_${prefix}_joint" type="fixed">
			<parent link="caster_large_${prefix}_link"/>
			<child link="wheel_large_${prefix}_link"/>
			<origin xyz="0 0 -0.130" pry="0 0 0"/>
			<axis xyz="0 1 0"/>
		</joint>

		<link name="wheel_large_${prefix}_link">
			<visual>
				<geometry>
					<cylinder length="0.040" radius="0.080"/>
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
				<material name="black"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="0.040" radius="0.080"/>
				</geometry>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
			</collision>
			<xacro:default_wheel_inertial 
				mass="1.5" length="0.040" radius="0.080"
				x_offset="0.0" y_offset="0.0" z_offset="0.0"/>
		</link>
	</xacro:macro>

	<xacro:wheel_large prefix="left"/>
	<xacro:wheel_large prefix="right"/>

	<joint name="box_joint" type="fixed">
		<parent link="battery_link"/>
		<child link="box_link"/>
		<origin xyz="0 0 0.450" rpy="0 0 0"/>
	</joint>

	<link name="box_link">
		<visual>
			<geometry>
				<box size="0.720 0.500 0.360"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="gray"/>
		</visual>
		<collision>
			<geometry>
				<box size="0.720 0.500 0.360"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:default_box_inertial 
			mass="30" depth="0.720" width="0.500" height="0.360"
			x_offset="0.0" y_offset="0.0" z_offset="0.0"/>
	</link>

	<joint name="mast_joint" type="fixed">
		<parent link="box_link"/>
		<child link="mast_link"/>
		<origin xyz="0 0 0.420" rpy="0 0 0"/>
	</joint>

	<link name="mast_link">
		<visual>
			<geometry>
				<box size="0.100 0.100 0.480"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="lightgray"/>
		</visual>
		<collision>
			<geometry>
				<box size="0.100 0.100 0.480"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:default_box_inertial 
			mass="10" depth="0.100" width="0.100" height="0.480"
			x_offset="0.0" y_offset="0.0" z_offset="0.0"/>
	</link>

	<joint name="table_joint" type="fixed">
		<parent link="mast_link"/>
		<child link="table_link"/>
		<origin xyz="0 0 0.246" rpy="0 0 0"/>
	</joint>

	<link name="table_link">
		<visual>
			<geometry>
				<box size="0.200 0.200 0.006"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="ivory"/>
		</visual>
		<collision>
			<geometry>
				<box size="0.200 0.200 0.006"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:default_box_inertial 
			mass="1" depth="0.200" width="0.200" height="0.006"
			x_offset="0.0" y_offset="0.0" z_offset="0.0"/>
	</link>

	<!-- velodyne -->
	<joint name="velodyne_base_joint" type="fixed">
		<parent link="table_link"/>
		<child link="velodyne_base_link"/>
		<origin xyz="0 0 0.003" rpy="0 0 0"/>
	</joint>

	<link name="velodyne_base_link">
		<visual>
			<geometry>
				<cylinder length="${velodyne_base_length}" radius="${velodyne_diameter/2}"/>
			</geometry>
			<origin xyz="0 0 ${velodyne_base_length/2}" rpy="0 0 0"/>
			<material name="darkgray"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${velodyne_base_length}" radius="${velodyne_diameter/2}"/>
			</geometry>
			<origin xyz="0 0 ${velodyne_base_length/2}" rpy="0 0 0"/>
		</collision>
		<xacro:default_cylinder_inertial 
			mass="1.0" length="${velodyne_base_length}" radius="${velodyne_diameter/2}"
			x_offset="0.0" y_offset="0.0" z_offset="${velodyne_base_length/2}"/>
	</link>

	<joint name="velodyne_top_joint" type="continuous">
		<parent link="velodyne_base_link"/>
		<child link="velodyne_top_link"/>
		<origin xyz="0 0 ${velodyne_base_length}" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<link name="velodyne_top_link">
		<visual>
			<geometry>
				<mesh filename="package://infant_description/meshes/velodyne_top.dae"/>
			</geometry>
			<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${velodyne_top_length}" radius="${velodyne_diameter/2}"/>
			</geometry>
			<origin xyz="0 0 ${velodyne_top_length/2}" rpy="0 0 0"/>
		</collision>
		<xacro:default_cylinder_inertial 
			mass="0.0001" length="${velodyne_top_length}" radius="${velodyne_diameter/2}"
			x_offset="0.0" y_offset="0.0" z_offset="${velodyne_top_length/2}"/>
	</link>

	<joint name="velodyne_laser1_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser1_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 0"/>
	</joint>

	<link name="velodyne_laser1_link">
		<visual>
			<geometry>
				<box size="${velodyne_laser_depth} ${velodyne_laser_width} ${velodyne_laser_height}"/>
			</geometry>
			<origin xyz="${velodyne_laser_depth/2} 0 0" rpy="${pi/2} 0 0"/>
			<material name="lase_black"/>
		</visual>
		<collision>
			<geometry>
				<box size="${velodyne_laser_depth} ${velodyne_laser_width} ${velodyne_laser_height}"/>
			</geometry>
			<origin xyz="${velodyne_laser_depth/2} 0 0" rpy="${pi/2} 0 0"/>
		</collision>
		<xacro:default_box_inertial
			mass="0.0001" 
			depth="${velodyne_laser_depth}" 
			width="${velodyne_laser_width}" 
			height="${velodyne_laser_height}"
			x_offset="${velodyne_laser_depth/2}"
			y_offset="0.0"
			z_offset="0.0"/>
	</link>

	<joint name="velodyne_laser2_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser2_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 ${pi/2}"/>
	</joint>

	<link name="velodyne_laser2_link"/>

	<joint name="velodyne_laser3_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser3_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 ${pi}"/>
	</joint>

	<link name="velodyne_laser3_link"/>
	
	<joint name="velodyne_laser4_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser4_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 -${pi/2}"/>
	</joint>

	<link name="velodyne_laser4_link"/>

	<joint name="velodyne_laser5_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser5_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 ${pi/4}"/>
	</joint>

	<link name="velodyne_laser5_link"/>

	<joint name="velodyne_laser6_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser6_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 ${3*pi/4}"/>
	</joint>

	<link name="velodyne_laser6_link"/>

	<joint name="velodyne_laser7_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser7_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 -${pi/4}"/>
	</joint>

	<link name="velodyne_laser7_link"/>

	<joint name="velodyne_laser8_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser8_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 -${3*pi/4}"/>
	</joint>

	<link name="velodyne_laser8_link"/>
	
	<joint name="velodyne_laser9_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser9_link"/>
		<origin xyz="0 0 ${0.0069204+(velodyne_laser_height/2)}" rpy="-${pi/2} 0 0"/>
	</joint>

	<link name="velodyne_laser9_link"/>

	<!-- transmission -->
	<transmission name="wheel_left_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="wheel_left_joint">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="wheel_left_motor">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>


	<transmission name="wheel_right_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="wheel_right_joint">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="wheel_right_motor">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="velodyne_top_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="velodyne_top_joint">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="velodyne_top_motor">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

		

</robot>
