dynamixel_arm:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    #arm_position_trajectry_controller:
    #   type: "position_controllers/JointTrajectoryController"
    #   joints:
    #       - joint1
    #       - joint2
    #       - joint3
    #       - joint4
    #       - joint5
    #       - joint6

    #   constraints:
    #       goal_time: 1.0
    #       stopped_velocity_tolerance: 0.03
    #       joint1:
    #           trajectry: 0.05
    #           goal: 0.02
    #       joint2:
    #           trajectry: 0.05
    #           goal: 0.02
    #       joint3:
    #           trajectry: 0.05
    #           goal: 0.02
    #       joint4:
    #           trajectry: 0.05
    #           goal: 0.02
    #       joint5:
    #           trajectry: 0.05
    #           goal: 0.02
    #       joint6:
    #           trajectry: 0.05
    #           goal: 0.02
                
    #   gains: 
    #       joint1: {p: 700, i: 0.01, d: 25, i_clamp: 1}
    #       joint2: {p: 10000, i: 100, d: 100, i_clamp: 1}
    #       joint3: {p: 4500, i: 35, d: 1, i_clamp: 1}
    #       joint4: {p: 5500, i: 60, d: 2, i_clamp: 1}
    #       joint5: {p: 1000, i: 30, d: 0.01, i_clamp: 1}
    #       joint6: {p: 900, i: 0.1, d: 0.01, i_clamp: 1}

    #       state_publish_rate: 25
    #       action_monitor_rate: 10
    #       hold_trajectory_duration: 0



    joint1_position_controller:
        type: position_controllers/JointPositionController
        joint: joint1
        pid: {p: 100, i: 0.01, d: 10.0}

    joint2_position_controller: 
       type: position_controllers/JointPositionController
       joint: joint2
       pid: {p: 100, i: 0.01, d: 10.0}

    joint3_position_controller:
       type: position_controllers/JointPositionController
       joint: joint3
       pid: {p: 100, i: 0.01, d: 10.0}
    
    joint4_position_controller:
       type: position_controllers/JointPositionController
       joint: joint4
       pid: {p: 100, i: 0.01, d: 10.0}
    
    joint5_position_controller:
       type: position_controllers/JointPositionController
       joint: joint5
       pid: {p: 100, i: 0.01, d: 10.0}
    
    joint6_position_controller:
       type: position_controllers/JointPositionController
       joint: joint6
       pid: {p: 100, i: 0.01, d: 10.0}
    
    joint7_position_controller:
       type: position_controllers/JointPositionController
       joint: joint7
       pid: {p: 100, i: 0.01, d: 10.0}
